// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALIviFbEKuun2OdQrnbAQJnpFFSvbcWeE',
    appId: '1:743757469889:web:e70212205b7fea8fb09c40',
    messagingSenderId: '743757469889',
    projectId: 'motivation-app-12d71',
    authDomain: 'motivation-app-12d71.firebaseapp.com',
    storageBucket: 'motivation-app-12d71.appspot.com',
    measurementId: 'G-LV9QVL1TBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXzVFQ4VBHj-1BbS8sY1FfstBng7Njk9Q',
    appId: '1:743757469889:android:89857ea939f59bb4b09c40',
    messagingSenderId: '743757469889',
    projectId: 'motivation-app-12d71',
    storageBucket: 'motivation-app-12d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTjJviaYNS7pGBhG0E3-x6ua_wsv8qKgc',
    appId: '1:743757469889:ios:2e6d48ed71df3a97b09c40',
    messagingSenderId: '743757469889',
    projectId: 'motivation-app-12d71',
    storageBucket: 'motivation-app-12d71.appspot.com',
    iosBundleId: 'com.example.motivationalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTjJviaYNS7pGBhG0E3-x6ua_wsv8qKgc',
    appId: '1:743757469889:ios:94306d51e418798ab09c40',
    messagingSenderId: '743757469889',
    projectId: 'motivation-app-12d71',
    storageBucket: 'motivation-app-12d71.appspot.com',
    iosBundleId: 'com.example.motivationalApp.RunnerTests',
  );
}
